# modules/programs/vim.nix
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.programs.vim;
in {
  config = mkIf cfg.enable {
    environment.systemPackages = [ pkgs.vim ] ++ cfg.plugins;
    
    # Set vim as default editor if requested
    environment.variables = mkIf cfg.defaultEditor {
      EDITOR = "vim";
      VISUAL = "vim";
    };
    
    # Generate .vimrc file
    home.file.".vimrc".text = ''
      " Generated by nix-env-loader
      
      " Load plugins
      ${concatMapStrings (plugin: ''
        " Plugin: ${plugin.name}
        set runtimepath+=${plugin}
      '') cfg.plugins}
      
      " User's extra configurations
      ${cfg.extraConfig}
    '';
  };
}
