# modules/programs/vim.nix
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.programs.vim;

  # Helper function for creating activation scripts
  mkActivationScript = name: text: deps: {
    inherit name text deps;
  };
in
{
  options = {
    programs.vim = {
      enable = mkEnableOption "vim editor";

      defaultEditor = mkOption {
        type = types.bool;
        default = false;
        description = "Whether to set vim as the default editor.";
      };

      plugins = mkOption {
        type = types.listOf types.package;
        default = [ ];
        description = "List of vim plugins to install.";
      };

      extraConfig = mkOption {
        type = types.lines;
        default = "";
        description = "Extra configuration to add to .vimrc.";
      };
    };
  };

  config = mkIf cfg.enable {
    # Add required packages
    environment.systemPackages = [ pkgs.vim ] ++ cfg.plugins;

    # Set vim as default editor if requested
    environment.variables = mkIf cfg.defaultEditor {
      EDITOR = "vim";
      VISUAL = "vim";
    };

    # Define the activation script for Vim setup
    home.activationScripts.vimSetup = mkActivationScript "vimSetup" ''
            echo "Setting up Vim configuration..."
      
            # Create .vimrc with all configurations
            cat > "$TMP_DIR/.vimrc" << 'EOL'
      " Generated by nix-env-loader

      " Load plugins
      ${concatMapStrings (plugin: ''
      " Plugin: ${plugin.name}
      set runtimepath+=${plugin}
      '') cfg.plugins}

      " User's extra configurations
      ${cfg.extraConfig}
      EOL
    '' [ "homeFiles" ];
  };
}
